server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/3129571932/spring-config.git
          search-paths:
            - spring-config
          skip-ssl-validation: true
      label: master
      #rabbitmq 相关配置
  rabbitmq:
    host: 192.168.1.5
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'