server:
  port: 80
spring:
  application:
    name: zkOrder
  cloud:
    zookeeper:
      connect-string: 192.168.181.133:2181
      base-sleep-time-ms: 100000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.5:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456